---
- name: Convert json to idm format
  json_to_idm:
    json_input: '{{ json_list }}'
  register: result
- set_fact:
    users: "{{ result.meta.users }}"
    user_groups: "{{ result.meta.user_groups }}"
- debug: var=users
- debug: var=user_groups
#- set_fact:
#    user_groups: "{{ clean_json.user_groups }}"
#    users: "{{ clean_json.users }}"
#    atlassian_users: "{{ clean_json.atlassian_users }}"
#    atlassian_groups: "{{ clean_json.atlassian_groups }}"
#- debug: var=atlassian_users
#- debug: var=atlassian_groups

