---
- hosts: idm
  tasks:
    - name: Set required ip address for forward dns
      set_fact:
        dns_records: "{{ dns_records|combine({
          'forward': { 'ip': openstack.private_v4 }, 'reverse': { 'hostname': openstack.private_v4.split('.')[-1] }
        }, recursive=True) }}"
      when: 
      - hosting_infrastructure == 'openstack'

    - debug:
        msg: "{{ dns_records }}"