---

- name: Install Quay Enterprise
  hosts: quay_enterprise
  tasks:
    - name: Configure Docker
      include_role:
        name: config-container-storage-setup
      when: docker_install|default(false)

    - name: Install Docker
      include_role:
        name: config-docker
      when: docker_install|default(false)

    - name: Include Quay Role
      include_role:
        name: config-quay-enterprise

