---

- name: 'Update local access for account:{{ user_name }}'
  hosts: all
  roles:
    - role: user-management/manage-local-user-password
    - role: user-management/manage-local-user-ssh-authkeys
    - role: manage-sshd-config
  tags:
    - manage-local-user-access

