---

- name: 'Use a unique temporary directory to store the config files pre-assemble'
  tempfile:
    state: directory
    prefix: dns-zone
  register: dns_zone_tempdir
  notify:
  - 'cleanup temp'

- name: 'Store away the temporary configuration files directory name'
  set_fact:
    dns_zone_temp_config_dir: '{{ dns_zone_tempdir.path }}'
