---

- name: Ensure the final view directory exists
  file:
    path: "{{ dns_zone_temp_config_dir }}/view"
    state: directory

- include_tasks: process-zones.yml
  with_items:
    -  "{{ dns_data.views }}"
  loop_control:
    loop_var: "view"

- name: Assemble the final view configuration
  assemble:
    src: "{{ dns_zone_temp_config_dir }}/view"
    dest: "/etc/named/named.conf.view"
  notify: restart named

- name: Setup ACLs
  vars:
    named_views: "{{ dns_data.views }}"
  template:
    src: named/acl.j2
    dest: /etc/named/named.conf.acl
    owner: named
    group: named
    mode: 0660
  notify: restart named
