---
- include_tasks: prereqs.yml
- name: Pull data from Google spreadsheet
  fetch_data_gsheets:
    spreadsheet_url: '{{ spreadsheet_url }}'
    worksheet_name: '{{ worksheet_name }}'
    credentials_src: '{{ credentials_src }}'
    state: 'present'
  register: result
- set_fact:
    json_list: "{{ result.meta.json }}"
- debug: var=json_list

